```{r child_all_gene_list, context="server"}
output$all_gene_list <- renderDataTable({
	options(warn=0)

	go <- igo()
	sym.all <- toupper(isolate(isym.all()))
	sym.all.1 <- isym.all.1()

	if(sym.all == "" || is.null(sym.all.1) || !grepl(sym.all,sym.all.1,ignore.case=T)){
	    validate(
	      if(sym.all==""){
	      	need(sym.all!="", "Please type in a full or partial gene name.\nGenes that match your query will be shown here.")
	      }else{
		    need(!is.null(sym.all.1),paste0("No gene symbol has a prefix '",sym.all,"'"))
 		  }
		)
	}else{
		eids <- df$eid[grep(paste0("^",sym.all),df$sym,ignore.case=T)]
		# stop(paste(sym.all.1,collapse=","))

		dt <- df %>% 
			filter(eid %in% eids) %>%
			arrange(efficacy,desc(selectivity))

		dt <- dt %>% select(sym, efficacy, selectivity) %>%
			mutate(selected = as.numeric(sym == sym.all.1)) %>%
			mutate(sym = paste0('<a href="https://www.genecards.org/cgi-bin/carddisp.pl?gene=',sym,'" target="_blank">',sym,'</a>')) %>%
			`colnames<-`(c("Gene","Efficacy","Selectivity","selected")) %>%
			datatable(extensions = 'Scroller', 
				options = list(
				  columnDefs = list(list(targets = 4, visible = FALSE)),
	　　			  rowReorder = TRUE,
				  deferRender = TRUE,
				  scrollY = 1000,
				  pageLength=200,
				  scroller = TRUE,
				  order = list(list(2, 'asc'), list(3, 'desc'))),
				selection=list(mode="none"),
				editable=FALSE,escape=FALSE) %>%
			    formatStyle(
			  4,
			  target = 'row',
			  backgroundColor = styleEqual(c(1,0), c('#ffcccb', NA))
			)
		return(dt)
	}
})
```
```{r}
dataTableOutput("all_gene_list")
```
