```{r child_all_eff_sel, context="server"}
output$all_eff_sel <- renderPlotly({
	nlayer <- 31
	dthres <- 0.10
	suppressWarnings(
		p <- ggplot(df,aes(efficacy,selectivity)) +
			geom_vline(xintercept=c(0,thres.eff), col=c("grey50","grey70")) +
			geom_hline(yintercept=c(0,1),col=c("grey50","grey70")) + 
			stat_density_2d(aes(fill = stat(level)),geom="polygon",bins=nlayer) +
			scale_fill_gradientn(colors=rev(blues9)) + 
			geom_point(data=(df %>% filter(dens <= dthres)),
				aes(efficacy, selectivity,text=text), 
				color=blues9[9], size = 1) +
			theme_bw() +
		    theme(legend.position="none",plot.margin=unit(c(0,0,0,0),"lines"),
		      axis.text=element_text(size=10),axis.title=element_text(size=10),
		      plot.title=element_text(size=10),
		      axis.text.x = element_text(angle = 0)) +
			geom_point(data=dummy[1,],aes(efficacy,selectivity),col=NA,size=1) + # sym.all
			geom_point(data=dummy[2,],aes(efficacy,selectivity),col=NA,size=1) # sym.all.1
	)
	ply <- ggplotly(p,tooltip="text")
	ndata <- length(ply$x$data)
	sapply(ply$x$data,function(x)length(x$text))	
	for(i in seq(nlayer+4)){
		ply$x$data[[i]]$hoverinfo <- "none"
	}
	# warning(ndata)
	ply
})

observeEvent(input$goButton, {
	sym.all <- input$sym.all
	sym.all.1 <- input$sym.all.1
	grep.sym.all <- grepl(paste0("^",sym.all),df$sym,ignore.case=T)

	if(any(grep.sym.all)){
		df.1 <- df[grep.sym.all,] %>%
			mutate(text = paste0(sym.all,"<br />eff:",efficacy,", sel:",selectivity))

		# i.sym.all.1 <- which(grep.sym.all)[1]

		df.2 <- df.1[rep(match(sym.all.1,df.1$sym),2),]
		plotlyProxy('all_eff_sel') %>%
	        plotlyProxyInvoke("restyle", 
	        	list(x = list(df.1$efficacy), 
	        		y = list(df.1$selectivity),
	        		text = list(df.1$text),
	        		marker=list(color='rgba(255,128,0,1)',size=6)),
	        	list(36)) %>%
	        plotlyProxyInvoke("restyle", 
	        	list(x = list(df.2$efficacy), 
	        		y = list(df.2$selectivity),
	        		text = list(df.2$text),
	        		marker=list(color='rgba(255,25,0,1)',size=6)),
	        	list(37))
    }
})

observeEvent(input$sym.all.1, {
	sym.all.1 <- input$sym.all.1
	if(sym.all.1!="" && any(df$sym==sym.all.1)){
		i.sym.all.1 <- which(df$sym==sym.all.1)
		df.2 <- df[rep(i.sym.all.1,2),] %>%
			mutate(text = paste0(sym.all,"<br />eff:",efficacy,", sel:",selectivity))

		plotlyProxy('all_eff_sel') %>%
	        plotlyProxyInvoke("restyle", 
	        	list(x = list(df.2$efficacy), 
	        		y = list(df.2$selectivity),
	        		text = list(df.2$text),
	        		marker=list(color='rgba(255,25,0,1)',size=6)),
	        	list(37))
	    }
})

```
```{r}
plotlyOutput('all_eff_sel')
```
