```{r child_tsne, context="server"}
output$tsne <- renderPlotly({
	options(warn=0)

	eid2 <- isolate(ieid2())
	cs2 <- isolate(ics2())
	color2 <- icolor2()

	if(color2=="no gradient"){
		df.0 <- df.0 %>% arrange(d) %>% mutate(pri=d)
		col <- scale_color_identity()
	}else if(color2=="efficacy"){
		df.0 <- df.0 %>% arrange(desc(efficacy)) %>% mutate(pri=-efficacy)
		col <- scale_colour_gradientn(colours = brewer.pal(9,"YlGn")[4:9])
	}else if(color2=="selectivity"){
		df.0 <- df.0 %>% arrange(selectivity) %>% mutate(pri=selectivity)
		col <- scale_colour_gradientn(colours = brewer.pal(9,"YlGnBu")[4:9])
	}

	## > thres.eff | <  lik2 : grey (back)
	## < thres.eff & > lik2 : color

	p <- ggplot(data=df.0,aes(text=text)) +
	    geom_point(aes(x,y,col=pri),size=.5) + col +
		theme_bw() +
	    theme(legend.position="none",
			plot.margin=unit(c(0,0,0,0),"lines"),
			axis.text=element_blank(),
			axis.title=element_blank(),
			plot.title=element_blank(),
			axis.ticks=element_blank())

	if(eid2==""){
		p <- p + 
		    geom_point(data=dummy[1,], aes(x,y), col=NA,size=1) +
		    geom_point(data=dummy[2,],aes(x,y), col=NA,size=1)
	}else{
		cs.idx2 <- paste0("mem",match(cs2,cs))
		cl2 <- (df.0 %>% filter(eid==eid2))[[cs.idx2]]
		if(cl2 == "NA"){

			eids <- eid2
		}else{
			eids <- df.0[df.0[[cs.idx2]] %in% cl2,"eid"]
		}


		df.2 <- df.0  %>% filter(eid %in% eids)
		df.3 <- df.2 %>% filter(eid == eid2)

		if(nrow(df.2)>0){
			p <- p +
				geom_point(data=df.2,aes(x,y),col="rgba(255,128,0,1)",size=1.2) # 6th trace, lik < lik2
		}
		if(nrow(df.3)>0){
			p <- p +
				geom_point(data=df.3,aes(x,y),col="rgba(255,25,0,1)",size=1.2) # 7th trace, lik >= lik2
		}
	}

	ply <- ggplotly(p,tooltip="text")
	ply
})


observeEvent(toListen(),{
	eid2 <- input$eid2
	cs2 <- input$cs2

	if(eid2==""){
		return(NULL)
	}else{
		cs.idx2 <- paste0("mem",match(cs2,cs))
		cl2 <- (df.0 %>% filter(eid==eid2))[[cs.idx2]]
		if(cl2 == "NA"){
			eids <- eid2
		}else{
			eids <- df.0[df.0[[cs.idx2]] %in% cl2,"eid"]
		}

		grep.eids <- which(df.0$eid %in% eids)

		# warning(paste(gen.path2,eid2=="",lik2,collapse=" "))

		if(any(grep.eids)){
			df.1 <- df.0[grep.eids,] %>%
				mutate(text=paste0(sym,
			        "<br />eff:",efficacy,", sel:",selectivity,
			        "<br />clust:",mem1,",",mem2,",",mem3))

			df.2 <- df.1[rep(match(eid2,eids),2),]

			plotlyProxy('tsne') %>%
		        plotlyProxyInvoke("restyle", 
		        	list(x = list(df.1$x), 
		        		y = list(df.1$y),
		        		text = list(df.1$text),
		        		marker=list(color='rgba(255,128,0,1)',size=6)),
		        	list(1)) %>%
		        plotlyProxyInvoke("restyle", 
		        	list(x = list(df.2$x), 
		        		y = list(df.2$y),
		        		text = list(df.2$text),
		        		marker=list(color='rgba(255,25,0,1)',size=6)),
		        	list(2))
	    }
	}
},ignoreInit=TRUE)
```
```{r}
plotlyOutput('tsne')
```
