```{r child_summary_efficacy_selectivity, context="server"}
output$summary_efficacy_selectivity <- renderPlotly({
	eid2 <- isolate(ieid2())
	cs2 <- isolate(ics2())
	color2 <- icolor2()


	if(color2=="no gradient"){
		df.0 <- df.0 %>% mutate(pri="navy")
		col <- scale_color_identity()
	}else if(color2=="efficacy"){
		df.0 <- df.0 %>% mutate(pri=-efficacy)
		col <- scale_colour_gradientn(colours = brewer.pal(9,"YlGn")[4:9])
	}else if(color2=="selectivity"){
		df.0 <- df.0 %>% mutate(pri=selectivity)
		col <- scale_colour_gradientn(colours = brewer.pal(9,"YlGnBu")[4:9])
	}

	## > thres.eff | <  lik2 : grey (back)
	## < thres.eff & > lik2 : color

	# warning(length(eids))

	p <- ggplot(df.0,aes(text=text)) +
		geom_vline(xintercept=thres.eff, col="grey70") +
		geom_hline(yintercept=c(0,1),col=c("grey50","grey70")) + 
		geom_point(data = (df.0 %>% filter(dens > 0.07) %>% mutate(text="")),
			aes(efficacy, selectivity, col=pri), size = .5) +
		geom_point(data = (df.0 %>% filter(dens <= 0.07)),
			aes(efficacy, selectivity, col=pri), size = .5) + col +
		# geom_point(aes(efficacy, selectivity, col=pri), size = .5) + col +
		theme_bw() +
	    theme(legend.position="none",plot.margin=unit(c(0,0,0,0),"lines"),
	      axis.text=element_text(size=10),axis.title=element_text(size=10),
	      plot.title=element_text(size=10),
	      axis.text.x = element_text(angle = 0))

	# if(is.null(eids)||eids==""){
	if(eid2==""){
		p <- p + 
			geom_point(data=dummy[1,],aes(efficacy,selectivity),col=NA,size=1.2) + # 6th trace, lik < lik2
			geom_point(data=dummy[2,],aes(efficacy,selectivity),col=NA,size=1.2) # 7th trace, lik >= lik2
	}else{
		cs.idx2 <- paste0("mem",match(cs2,cs))
		cl2 <- (df.0 %>% filter(eid==eid2))[[cs.idx2]]
		if(cl2 == "NA"){
			eids <- eid2
		}else{
			eids <- df.0[df.0[[cs.idx2]] %in% cl2,"eid"]
		}

		df.2 <- df.0  %>% filter(eid %in% eids)
		df.3 <- df.2 %>% filter(eid == eid2)

		# warning(nrow(df.2))
		# warning(nrow(df.3))

		if(nrow(df.2)>0){
			p <- p +
				geom_point(data=df.2,aes(efficacy,selectivity),col='rgba(255,128,0,1)',
					size=1.2) # 6th trace, lik < lik2
		}
		if(nrow(df.3)>0){
			p <- p +
				geom_point(data=df.3,aes(efficacy,selectivity),col='rgba(255,25,0,1)',
					size=1.2) # 7th trace, lik >= lik2
		}
	}		

	ply <- ggplotly(p,tooltip="text")
	sapply(ply$x$data,function(x)length(x$x))
	for(i in 1:3)ply$x$data[[i]]$hoverinfo <- "none"
	ply
})

observeEvent(toListen(),{
	eid2 <- input$eid2
	cs2 <- input$cs2

	if(eid2==""){
		return(NULL)
	}else{
		cs.idx2 <- paste0("mem",match(cs2,cs))
		cl2 <- (df.0 %>% filter(eid==eid2))[[cs.idx2]]
		if(cl2 == "NA"){
			eids <- eid2
		}else{
			eids <- df.0[df.0[[cs.idx2]] %in% cl2,"eid"]
		}

		grep.eids <- which(df.0$eid %in% eids)

		if(any(grep.eids)){
			df.1 <- df.0[grep.eids,] %>%
				mutate(text=paste0(sym,
			        "<br />eff:",efficacy,", sel:",selectivity,
			        "<br />clust:",mem1,",",mem2,",",mem3))


			df.2 <- df.1[rep(match(eid2,eids),2),]

			plotlyProxy('summary_efficacy_selectivity') %>%
		        plotlyProxyInvoke("restyle", 
		        	list(x = list(df.1$efficacy), 
		        		y = list(df.1$selectivity),
		        		text = list(df.1$text),
		        		marker=list(color='rgba(255,128,0,1)',size=6)),
		        	list(5)) %>%
		        plotlyProxyInvoke("restyle", 
		        	list(x = list(df.2$efficacy), 
		        		y = list(df.2$selectivity),
		        		text = list(df.2$text),
		        		marker=list(color='rgba(255,25,0,1)',size=6)),
		        	list(6))
	    }
	}
},ignoreInit=TRUE)

```
```{r}
plotlyOutput('summary_efficacy_selectivity')
```
