```{r child_inter_cluster, context="server"}
output$inter_cluster <- renderPlotly({
	options(warn=-1)

	if(0){
		eid2 <- "2879"
		cs2 <- "small"
		coef2 <- s3readRDS(paste0("coef_ess_19q3/2879.rds"),bucket="depmap")
	}else{
		eid2 <- ieid2()
		cs2 <- ics2()
		coef2 <- icoef2()
	}

	cs.idx2 <- paste0("mem",match(cs2,cs))


	if(eid2==""){
	    validate(
	      	need(eid2!="",
	      		"Please choose an essential gene and a cluster size (default:Small).\nSpearman correlation coefficients across the essential genes will be shown here.")
		)
	}else{
		sym.all2 <- df.0$sym.all[df.0$eid == eid2]
		sym2 <- df.0$sym[df.0$eid == eid2]
		cl2 <- df.0[df.0$eid == eid2,cs.idx2]

		coef.1 <- data.frame(coef=coef2,eid=names(coef2),stringsAsFactors=FALSE) %>%
			left_join(df.0,by="eid") %>%
			filter(eid != eid2)

		mem <- as.character(coef.1[[cs.idx2]])
		mem[is.na(mem)] <- "none"

		med.mem <- tapply(coef.1$coef,mem,mean)
		o <- order(med.mem,decreasing=F)
		clust.levs <- names(med.mem)[o]

		coef.1 <- coef.1 %>% mutate(mem=factor(mem,levels=clust.levs)) %>%
			mutate(text=paste0(sym,"(",mem,") - ",sym2,"(",cl2,")<br />",coef))

		sum.coef.1 <- coef.1 %>% 
			group_by(mem) %>% 
			summarize(maxs=max(coef),mins=min(coef),mids=mean(coef)) %>%
			arrange(mids) %>%
			mutate(mem=factor(mem,levels=clust.levs))

		suppressWarnings({ # doesn't work..
			pvio <- ggplot(sum.coef.1, aes(x=mem,y=mids,color=mem)) +
				geom_linerange(aes(ymin=mins,ymax=maxs))+
				geom_jitter(data=coef.1,aes(x=mem,y=coef),height=0, width=0.1, size=.3,
					color="black")+
				coord_flip() +
				theme_bw() +
				theme(legend.position="none",plot.margin=unit(c(0,0,0,0),"lines"),
				  axis.text=element_text(size=10),axis.title=element_text(size=10),
				  plot.title=element_text(size=15, hjust=0.5),
				  axis.text.x = element_text(angle = 0)) +
				ggtitle(paste0(sym.all2, "\t(",cs2," size clusters)")) + 
				labs(x="",y="Spearman correlation between genes")
			ply <- ggplotly(pvio) %>% 
				add_segments(x = 0, xend = 0, y = 0, yend = 600, 
					line=list(color="black")) %>% 
				config(displayModeBar=F)
			ndata <- length(ply$x$data)
			for(i in seq(ndata-1))ply$x$data[[i]]$hoverinfo <- "none"
		    ply$x$data[[ndata]]$text <- coef.1$text
		 })
		return(ply)
	}
})
```

```{r}
plotlyOutput("inter_cluster")
```
