```{r child_sidebar2}


pickerInput(
	inputId = "eid2",
	label = h4("Essential gene:"),
	choices = c("",eids.ess),
  selected = "",
	options = list(`live-search` = TRUE))

## 0. sidebar (highlight)
HTML("<hr>")
sliderTextInput("cs2",h4("Cluster size:"),
  choices = cs,
  selected =cs[1],
  hide_min_max = TRUE,
  grid=TRUE
 )

selectInput("color_code2",h5("Color coded by:"),
  choices=c("selectivity","efficacy"),
  selected="selectivity")
```

```{r child_reactive2, context="server"}
ieid2 <- reactive(input$eid2)
icolor2 <- reactive(input$color_code2)
ics2 <- reactive(input$cs2)

toListen <- reactive({
  list(
    input$eid2, # eid2
    input$cs2
    )
})

icoef2 <- reactive({
  if(is.null(input$eid2)||input$eid2==""){
    return(NULL)
  }else{
    # s3readRDS(paste0("coef_ess_19q3/",input$eid2,".rds"),bucket="depmap")
    coef[input$eid2,]
  }
})

ief2 <- reactive({
  if(is.null(input$eid2)||input$eid2==""){
    return(NULL)
  }else{
    # s3readRDS(paste0("scores_all_19q3/",input$eid2,".rds"),bucket="depmap")
    p.scores[input$eid2,]
  }
})

shinyInput <- function(FUN, query, id, ...) {
  inputs <- as.character(FUN(paste0(id, query), ...))
}

##
observeEvent(input$c1_button,{
  eid2 <- input$eid2
  cl2 <- sub("button_","",input$c1_button)

  updateSliderTextInput(session,
    inputId = "cs2",
    selected = "Small"
  )
  eids <- df.0$eid[df.0$mem1==cl2]
  # stop(paste(eids,collapse=";"))

  if(!any(eid2 %in% eids)){
    dt <- df.0 %>% filter(eid %in% eids) %>%
      select(eid,efficacy, selectivity) %>%
      arrange(efficacy,desc(selectivity))
    eid2 <- dt$eid[1]
    updatePickerInput(session,
      inputId = "eid2",
      selected = eid2)
  }
}, ignoreInit = TRUE)


##
observeEvent(input$c2_button,{
  eid2 <- input$eid2
  cl2 <- sub("button_","",input$c2_button)

  updateSliderTextInput(session,
    inputId = "cs2",
    selected = "Medium"
  )
  eids <- df.0$eid[df.0$mem2==cl2]
  # stop(paste(eids,collapse=";"))

  if(!any(eid2 %in% eids)){
    dt <- df.0 %>% filter(eid %in% eids) %>%
      select(eid,efficacy, selectivity) %>%
      arrange(efficacy,desc(selectivity))
    eid2 <- dt$eid[1]
    updatePickerInput(session,
      inputId = "eid2",
      selected = eid2)
  }
}, ignoreInit = TRUE)


##
observeEvent(input$c3_button,{
  eid2 <- input$eid2
  cl2 <- sub("button_","",input$c3_button)

  updateSliderTextInput(session,
    inputId = "cs2",
    selected = "Large"
  )
  eids <- df.0$eid[df.0$mem3==cl2]
  # stop(paste(eids,collapse=";"))

  if(!any(eid2 %in% eids)){
    dt <- df.0 %>% filter(eid %in% eids) %>%
      select(eid,efficacy, selectivity) %>%
      arrange(efficacy,desc(selectivity))
    eid2 <- dt$eid[1]
    updatePickerInput(session,
      inputId = "eid2",
      selected = eid2)
  }
}, ignoreInit = TRUE)
```
