```{r child_intra_cluster, context="server"}
output$intra_cluster <- renderVisNetwork({
	options(warn=0)

	if(0){
		eid2 <- "2879" # gpx4
		eid2 <- "598" # bcl2l1
		eid2 <- "64978" # mrpl38
		cs2 <- "Small"
		cs2 <- "Large"
		# coef2 <- s3readRDS(paste0("coef_ess_19q3/2879.rds"),bucket="depmap")
	}else{
		eid2 <- ieid2()
		cs2 <- ics2()
	}

	if(eid2==""){
	    validate(
	      	need(eid2!="",
	      		"Please choose an essential gene and a cluster size (default:Small).\nSpearman correlation coefficients between genes (> 0.1) within the cluster will be shown here.")
		)
	}else{
		cs.idx2 <- paste0("mem",match(cs2,cs))
		cl2 <- (df.0 %>% filter(eid==eid2))[[cs.idx2]]
		if(is.na(cl2)){
			return(NULL)
		}

		s3load(paste0("graph_19q3/",cl2,".rda"),bucket="depmap") # nodes,edges

		p <- visNetwork(nodes, edges,width = "80%") %>%
		  visIgraphLayout() %>%
		  visNodes(
		    shape = "dot",
		    color = list(
		      background = "#0085AF",
		      border = "#013848",
		      highlight = "#FF8000"
		    ),
		    shadow = list(enabled = TRUE, size = 10)
		  ) %>%
		  visEdges(
		    shadow = FALSE,
		    color = list(color = "#7BA3C4", highlight = "#C62F4B")
		  ) %>%
		  visOptions(highlightNearest = list(enabled = T, degree = 1, hover = F),
		  			 nodesIdSelection = list(enabled =TRUE, selected = eid2),
		             selectedBy = "group") %>% 
		  visInteraction(dragView=FALSE,zoomView=FALSE) %>%
		  visLayout(randomSeed = 11)
	}
})
```
```{r}
visNetworkOutput("intra_cluster")
```