```{r child_lineage, context="server"}
output$lineage <- renderPlotly({
	gen.path2 <- igenclust2() 
	eid2 <- ieid2() 
	path2 <- ipath2() 
	clust2 <- iclust2()
	color2 <- icolor2() #c("gene,pathway","cluster","efficacy","selectivity"),

	this.ef <- ief2()
	gs2 <- igs2()

	if(is.null(gen.path2)|(gen.path2=="gene"&is.null(eid2))){
		return(NULL)
	}else if(gen.path2 %in% c("pathway","cluster")){
		stop("Choose a single gene (not pathway or cluster) to show this plot.")
	}

	# if(gen.path2=="gene"){
	# 	eids <- eid2
	# }else if(gen.path2=="pathway"){
	# 	eids <- gs2
	# }else if(gen.path2=="cluster"){
	# 	eids <- mems$eid[mems$mem==clust2]
	# }

	ef.1 <- data.frame(ef=this.ef,DepMap_ID=names(this.ef),stringsAsFactors=FALSE) %>%
		left_join(cl.info,by="DepMap_ID") %>%
		mutate(cell.name=sub("^([^_]+)_.+","\\1",CCLE_name))

	med.ef <- tapply(ef.1$ef,ef.1$disease,median)
	o <- order(med.ef,decreasing=F)
	cell.levs <- names(med.ef)[o]

	ef.1 <- ef.1 %>% 
		mutate(disease=factor(disease,levels=cell.levs)) %>%
		mutate(text=paste0(
			"Cell: ",cell.name,"<br />",
			"Type: ",disease,"<br />",
			"Subtype: ",disease_sutype,"<br />",
			"Sub-subtype: ",disease_sub_subtype,"<br />",
			"Efficacy: ",round(ef,3),"<br />"))

	pvio <- ef.1 %>%
		ggplot(aes(x=disease,y=ef)) +
		geom_violin(scale="area",aes(fill=disease,color=disease)) +
		geom_jitter(height = 0, width = 0.2, size=.5) +
		coord_flip() +
		theme_bw() +
		theme(legend.position="none",plot.margin=unit(c(0,0,0,0),"lines"),
		  axis.text=element_text(size=8),axis.title=element_text(size=10),
		  plot.title=element_text(size=10),
		  axis.text.x = element_text(angle = 0)) +
		labs(x="",y="Efficacy score",title="")

	ply <- ggplotly(pvio) %>% config(displayModeBar=F)
	ndata <- length(ply$x$data)
	for(i in seq(ndata-1))ply$x$data[[i]]$hoverinfo <- "none"
    ply$x$data[[ndata]]$text <- ef.1$text
	ply 
})
```
```{r}
plotlyOutput("lineage")
```

