```{r child_tsne, context="server"}
output$tsne <- renderPlotly({
	gen.path2 <- isolate(igenclust2())
	eid2 <- isolate(ieid2())
	path2 <- isolate(ipath2())
	clust2 <- isolate(iclust2())

	color2 <- icolor2()
	lik2 <- ilik2()

	
	if(color2=="no gradient"){
		mems.0 <- mems %>% arrange(d) %>% mutate(pri=d)
		col <- scale_color_identity()
	}else if(color2=="efficacy"){
		mems.0 <- mems %>% arrange(desc(efficacy)) %>% mutate(pri=-efficacy)
		col <- scale_colour_gradientn(colours = brewer.pal(9,"YlGn")[4:9])
	}else if(color2=="selectivity"){
		mems.0 <- mems %>% arrange(selectivity) %>% mutate(pri=selectivity)
		col <- scale_colour_gradientn(colours = brewer.pal(9,"YlGnBu")[4:9])
	}

	## > thres.eff | <  lik2 : grey (back)
	## < thres.eff & > lik2 : color

	p <- ggplot(data=mems.0,aes(text=text)) +
	    geom_point(data=(mems.0 %>% filter(lik < lik2) %>% mutate(text="")),
	    	aes(x,y),col="grey80",alpha=.5,size=.3) +
	    geom_point(data=(mems.0 %>% filter(lik >= lik2)),aes(x,y,col=pri),size=.5) + col +
		theme_bw() +
	    theme(legend.position="none",
			plot.margin=unit(c(0,0,0,0),"lines"),
			axis.text=element_blank(),
			axis.title=element_blank(),
			plot.title=element_blank(),
			axis.ticks=element_blank())

	if(is.null(gen.path2)||
		(gen.path2=="essential gene"&&(is.null(eid2)||eid2==""))||
		(gen.path2=="pathway"&&(is.null(path2)||path2==""))||
		(gen.path2=="cluster"&&(is.null(clust2)||clust2==""))) {
		eids <- NULL
	}else 
	if(gen.path2=="essential gene"){
		eids <- eid2
	}else if(gen.path2=="pathway"){
		gs2 <- s3readRDS(paste0("msigdb_ess_19q2/",path2,".rds"),bucket="depmap")
		eids <- gs2
	}else if(gen.path2=="cluster"){
		eids <- mems$eid[mems$mem==clust2]
	}

	if(is.null(eids)){
		p <- p + 
		    geom_point(data=dummy[1,], aes(x,y), col=NA,size=1) +
		    geom_point(data=dummy[2,],aes(x,y), col=NA,size=1)
	}else{
		mems.1 <- mems.0  %>% filter(eid %in% eids)

		if(nrow(mems.1)==0)return(NULL)

		mems.2 <- mems.1 %>% filter(lik < lik2)
		mems.3 <- mems.1 %>% filter(lik >= lik2)

		if(nrow(mems.2)>0){
			p <- p +
				geom_point(data=mems.2,aes(x,y),col="grey50",size=1.2) # 6th trace, lik < lik2
		}
		if(nrow(mems.3)>0){
			p <- p +
				geom_point(data=mems.3,aes(x,y),col="red",size=1.2) # 7th trace, lik >= lik2
		}
	}

	ply <- ggplotly(p,tooltip="text")
	ply
})

observeEvent(toListen(),{
	## eids & < lik2 : grey (plotlyProxy)
	## eids & > lik : red (plotlyProxy)
	gen.path2 <- input$ess_gen_clust ## gene, orthogroup

	eid2 <- input$eid2
	path2 <- input$path2
	clust2 <- input$clust2

	lik2 <- input$lik2

	# eids <- define.eids.or.null(gen.path2,eid2,path2,clust2,mems)

	if(is.null(gen.path2)||
		(gen.path2=="essential gene"&&(is.null(eid2)||eid2==""))||
		(gen.path2=="pathway"&&(is.null(path2)||path2==""))||
		(gen.path2=="cluster"&&(is.null(clust2)||clust2==""))) {
		return(NULL)
	}else if(gen.path2=="essential gene"){
		eids <- eid2
	}else if(gen.path2=="pathway"){
		gs2 <- s3readRDS(paste0("msigdb_ess_19q2/",path2,".rds"),bucket="depmap")
		eids <- gs2
	}else if(gen.path2=="cluster"){
		eids <- mems$eid[mems$mem==clust2]
	}

	if(is.null(eids))return(NULL)

	mems.0 <- mems %>% filter(eid %in% eids)

	if(nrow(mems.0)==0)return(NULL)

	mems.1 <- mems.0 %>% filter(lik < lik2)
	mems.2 <- mems.0 %>% filter(lik >= lik2)

	if(nrow(mems.1)==1)mems.1 <- rbind(mems.1,mems.1)
	if(nrow(mems.2)==1)mems.2 <- rbind(mems.2,mems.2)

	# warning(mems.1$eff)
	# warning(mems.2$eff)

	col.neg <- ifelse(nrow(mems.1)>0,'rgba(127,127,127,1)','rgba(127,127,127,0)')
	col.pos <- ifelse(nrow(mems.2)>0,'rgba(255,0,0,1)','rgba(255,0,0,0)')

	plotlyProxy('tsne') %>%
	 	plotlyProxyInvoke("restyle", 
	        	list(x = list(mems.1$x),y = list(mems.1$y), text = list(mems.1$text),
	        		marker=list(color=col.neg,size=6)),2) %>%
		plotlyProxyInvoke("restyle", 
	        	list(x = list(mems.2$x),y = list(mems.2$y), text = list(mems.2$text),
        			marker=list(color=col.pos,size=6)),3)
})
```
```{r}
plotlyOutput('tsne')
```
